name: Build IBM Chess APK

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git zip unzip openjdk-17-jdk python3-pip \
            python3-virtualenv autoconf libtool libtool-bin pkg-config \
            zlib1g-dev libncurses5-dev libncursesw5-dev \
            libtinfo6 cmake libffi-dev libssl-dev \
            automake autopoint gettext m4

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: IBM-Chess-APK
          path: bin/*.apk
